sudo: required

services:
  - docker

language: node_js
node_js:
  10

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t jchancehud/star-signal:latest
  - docker push jchancehud/star-signal:latest
